// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fszsmlajstdrkzvxxqeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzenNtbGFqc3Rkcmt6dnh4cWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDExNjksImV4cCI6MjA2Mjc3NzE2OX0.mceMgrzVOqy-tmGuwveMfQdcHpDuT0KyGwP-MG22FbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);